package com.poem.lld.mapper;

import com.poem.lld.model.Poem;
import com.poem.lld.model.PoemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoemMapper2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    long countByExample(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int deleteByExample(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int insert(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int insertSelective(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    List<Poem> selectByExample(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    Poem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") Poem record, @Param("example") PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int updateByExample(@Param("record") Poem record, @Param("example") PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int updateByPrimaryKeySelective(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poem
     *
     * @mbg.generated Sat Oct 07 18:04:11 CST 2017
     */
    int updateByPrimaryKey(Poem record);
}